---
driver:
  name: docker

provisioner:
  name: puppet_apply
  mainfests_path: manifests
  modules_path: modules
  require_chef_for_busser: true

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:14.04
      use_cache: true


  - name: ubuntu16
    driver_config:
      image: ubuntu:16.04
      use_cache: true

  - name: centos
    driver_config:
      image: centos:6
      use_cache: true

suites:
  - name: default
    manifest: site.pp
